server:
  port: 5001
  
spring:  application:    name: zuul-gateway
    
eureka:
  instance:
    instance-id: zuul-5001    #the shown instance name
    prefer-ip-address: true       #the shown IP address
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka     #discovery cluster
      
      
info:       #info page
  discription: zuul gateway demo
  artifactId: $project.artifactId$
  version: $project.version$
  
  
zuul: 
  prefix: /djh
  ignored-services: 
    server-info-pervidor        #blocking "server-info-pervidor"  routes:    serverInfo.serviceId: server-info-pervidor
    serverInfo.path: /server-infomation/**           #routing "server-info-pervidor" to "server-infomation"